/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/model/lost.glb -k 
*/

import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

export function Model(props) {
  const { nodes } = useGLTF('./model/lost.glb');

  return (
    <group {...props} castShadow scale={2} >
      <mesh name="Circle" geometry={nodes.Circle.geometry} material={new MeshStandardMaterial()} scale={2} />
      <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={new MeshStandardMaterial()} />
    </group>
  )
}

useGLTF.preload('./model/lost.glb')
